"""Initial migration

Revision ID: 55200a34f725
Revises: d6600b1b60b9
Create Date: 2023-12-19 20:44:33.617044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55200a34f725'
down_revision = 'd6600b1b60b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('shared_by_user_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['movie_list.id'], ),
    sa.ForeignKeyConstraint(['shared_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_list')
    # ### end Alembic commands ###
